In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("data/retail_sales_dataset.csv")

In [3]:
df.head()

,transaction_id,transaction_date,customer_id,customer_gender,customer_age_group,customer_segment,product_id,product_name,category,brand,quantity,unit_price,discount_pct,sales_amount,payment_method,sales_channel,region
0,T0000001,2024-04-24,C000820,Other,35-44,Returning,P1082,Dumbbells,Sports,Brand 1,2,313.53,20,501.65,Debit Card,Online,North
1,T0000002,2025-07-12,C002849,Other,45-54,New,P1087,Running Shoes,Sports,Brand 3,1,366.16,0,366.16,Credit Card,Online,South
2,T0000003,2025-06-01,C019727,Male,55+,Returning,P1030,Sneakers,Clothing,Brand 3,1,27.99,0,27.99,Gift Card,In-Store,South
3,T0000004,2025-08-26,C009116,Male,25-34,VIP,P1058,Sunscreen,Beauty,Brand 1,2,102.01,15,173.42,Cash,In-Store,South
4,T0000005,2024-12-10,C003350,Male,45-54,New,P1028,Sneakers,Clothing,Brand 1,1,259.55,0,259.55,Cash,In-Store,Central

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      120000 non-null  str
 1   transaction_date    120000 non-null  str
 2   customer_id         120000 non-null  str
 3   customer_gender     120000 non-null  str
 4   customer_age_group  120000 non-null  str
 5   customer_segment    120000 non-null  str
 6   product_id          120000 non-null  str
 7   product_name        120000 non-null  str
 8   category            120000 non-null  str
 9   brand               120000 non-null  str
 10  quantity            120000 non-null  int64
 11  unit_price          120000 non-null  float64
 12  discount_pct        120000 non-null  int64
 13  sales_amount        120000 non-null  float64
 14  payment_method      120000 non-null  str
 15  sales_channel       120000 non-null  str
 16  region              120000 non-null  str
dtypes: float64(2), int64(2), str(13)
memory usage: 15.6 MB

In [5]:
df.shape

(120000, 17)

In [8]:
df.isnull().sum()

transaction_id        0
transaction_date      0
customer_id           0
customer_gender       0
customer_age_group    0
customer_segment      0
product_id            0
product_name          0
category              0
brand                 0
quantity              0
unit_price            0
discount_pct          0
sales_amount          0
payment_method        0
sales_channel         0
region                0
dtype: int64

In [9]:
df.isnull().sum()

transaction_id        0
transaction_date      0
customer_id           0
customer_gender       0
customer_age_group    0
customer_segment      0
product_id            0
product_name          0
category              0
brand                 0
quantity              0
unit_price            0
discount_pct          0
sales_amount          0
payment_method        0
sales_channel         0
region                0
dtype: int64

In [ ]:
df.duplicated().sum()
#df = df.drop_duplicates() if greater than 0 then use this

np.int64(0)

In [13]:
df.describe()

            quantity     unit_price   discount_pct   sales_amount
count  120000.000000  120000.000000  120000.000000  120000.000000
mean        1.662908     240.621785       5.496500     377.975454
std         1.014291     146.457057       8.193257     356.893357
min         1.000000       7.730000       0.000000       5.410000
25%         1.000000     102.010000       0.000000     136.860000
50%         1.000000     238.750000       0.000000     295.980000
75%         2.000000     379.000000      10.000000     461.500000
max         5.000000     493.510000      30.000000    2467.550000

In [14]:
df.dtypes

transaction_id            str
transaction_date          str
customer_id               str
customer_gender           str
customer_age_group        str
customer_segment          str
product_id                str
product_name              str
category                  str
brand                     str
quantity                int64
unit_price            float64
discount_pct            int64
sales_amount          float64
payment_method            str
sales_channel             str
region                    str
dtype: object

In [ ]:
#Convert transaction_date to datetime
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Verify
df['transaction_date'].dtype

dtype('<M8[us]')

In [16]:
#Check for invalid values
print("Quantity <= 0 :", (df['quantity'] <= 0).sum())
print("Unit Price <= 0 :", (df['unit_price'] <= 0).sum())
print("Sales Amount <= 0 :", (df['sales_amount'] <= 0).sum())

Quantity <= 0 : 0
Unit Price <= 0 : 0
Sales Amount <= 0 : 0

In [ ]:
#Verify Sales Amount
expected_sales = (
    df['quantity']
    * df['unit_price']
    * (1 - df['discount_pct'] / 100)
)

(df['sales_amount'] - expected_sales).abs().describe()

count    120000.00000
mean          0.00092
std           0.00154
min           0.00000
25%           0.00000
50%           0.00000
75%           0.00200
max           0.00500
dtype: float64

In [18]:
#Check categorical columns
categorical_cols = [
    'customer_gender',
    'customer_age_group',
    'customer_segment',
    'category',
    'brand',
    'payment_method',
    'sales_channel',
    'region'
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

customer_gender
customer_gender
Female    40268
Other     39906
Male      39826
Name: count, dtype: int64

customer_age_group
customer_age_group
35-44    24196
55+      24078
18-24    23941
45-54    23919
25-34    23866
Name: count, dtype: int64

customer_segment
customer_segment
VIP          30115
New          30020
Loyal        30014
Returning    29851
Name: count, dtype: int64

category
category
Sports         15218
Clothing       15156
Beauty         15073
Groceries      15034
Toys           15022
Electronics    15008
Home           14933
Books          14556
Name: count, dtype: int64

brand
brand
Brand 1    40240
Brand 2    39918
Brand 3    39842
Name: count, dtype: int64

payment_method
payment_method
Credit Card    24262
Cash           24034
PayPal         23998
Debit Card     23897
Gift Card      23809
Name: count, dtype: int64

sales_channel
sales_channel
Mobile App    40204
In-Store      40049
Online        39747
Name: count, dtype: int64

region
region
Central    24244
North      24075
South      24066
West       23950
East       23665
Name: count, dtype: int64

In [19]:
#create date features
df['year'] = df['transaction_date'].dt.year
df['month'] = df['transaction_date'].dt.month
df['month_name'] = df['transaction_date'].dt.month_name()
df['quarter'] = df['transaction_date'].dt.quarter
df['day'] = df['transaction_date'].dt.day
df['day_name'] = df['transaction_date'].dt.day_name()

In [ ]:
#save the cleaned dataset
df.to_csv("cleaned_retail_sales.csv", index=False)